"""Add detected_objects column

Revision ID: 62cd4b57be57
Revises: cb408c719e5e
Create Date: 2025-02-08 16:21:38.226308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cd4b57be57'
down_revision = 'cb408c719e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('detected_objects', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'detected_objects')
    # ### end Alembic commands ###
