"""Added detected_objects column

Revision ID: 6d6900f87ea1
Revises: 62cd4b57be57
Create Date: 2025-02-09 12:48:46.568994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6900f87ea1'
down_revision = '62cd4b57be57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photo', 'detected_objects',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photo', 'detected_objects',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
