"""Add generated_alt_text

Revision ID: cb408c719e5e
Revises: 
Create Date: 2025-02-08 15:12:00.767610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb408c719e5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('generated_alt_text', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'generated_alt_text')
    # ### end Alembic commands ###
